# config/ros2_control.yaml

controller_manager:
  ros__parameters:
    # how fast the controller manager updates
    update_rate: 50

    # publishes joint states for all your wheel joints
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - front_left_wheel_joint
        - front_right_wheel_joint
        - rear_left_wheel_joint
        - rear_right_wheel_joint

    # diff‐drive controller for arrow‐key teleop -> /cmd_vel
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names:
        - front_left_wheel_joint
        - rear_left_wheel_joint
      right_wheel_names:
        - front_right_wheel_joint
        - rear_right_wheel_joint
      wheel_separation: 1.734    # meters (front–rear distance)
      wheel_radius: 0.133        # meters
      cmd_vel_timeout: 0.5       # seconds before zeroing cmd_vel
      publish_rate: 20           # controller publish rate

