slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.0
    transform_publish_period: 0.02
    map_update_interval: 2.0
    mode: mapping
